#pragma once

#include <stdint.h>


namespace drivers::inverter {

enum class Temperatures1 : uint8_t {
	ModuleA, ModuleB, ModuleC, GateDriverBoard
};

enum class Temperatures2 : uint8_t {
	ControlBoard, RTD1, RTD2, RTD3
};

enum class Temperatures3 : uint8_t {
	Coolant, HotSpot, Motor, TorqueShudder
};

enum class MotorPosition : uint8_t {
	MotorAngle, MotorSpeed, ElectricalOutputFrequency, DeltaResolverFiltered, Count
};

enum class TorqueInformation : uint8_t {
	CommandedTorque, TorqueFeedback, Count
};

enum class TorqueCapability : uint8_t {
	TorqueCapability
};

enum class FaultFlags : uint8_t {
	PostFault, RunFault, Count
};

enum class PostFault : uint8_t {
	HARDWARE_GATE_DESATURATION, HARDWARE_OVERCURRENT, ACCELERATOR_SHORTED, ACCELERATOR_OPEN,
	CURRENT_SENSOR_LOW, CURRENT_SENSOR_HIGH, MODULE_TEMPERATURE_LOW, MODULE_TEMPERATURE_HIGH,
	CONTROL_PCB_TEMPERATURE_LOW, CONTROL_PCB_TEMPERATURE_HIGH, GATE_DRIVE_PCB_TEMPERATURE_LOW, GATE_DRIVE_PCB_TEMPERATURE_HIGH,
	SENSE_5V_LOW, SENSE_5V_HIGH, SENSE_12V_LOW, SENSE_12V_HIGH,
	SENSE_2p5V_LOW, SENSE_2p5V_HIGH, SENSE_1p5V_LOW, SENSE_1p5V_HIGH,
	DC_BUS_VOLTAGE_HIGH, DC_BUS_VOLTAGE_LOW, PRECHARGE_TIMEOUT, PRECHARGE_VOLTAGE_FAILURE,
	EEPROM_CHECKSUM_INVALID, EEPROM_DATA_OUT_OF_RANGE, EEPROM_UPDATE_REQUIRED, HARDWARE_DC_BUS_OVERVOLTAGE,
	BRAKE_SHORTED = 30, BRAKE_OPEN = 31
};

enum class RunFault : uint8_t {
	MOTOR_OVERSPEED, OVERCURRENT, OVERVOLTAGE, INVERTER_OVERTEMPERATURE,
	ACCELERATOR_INPUT_SHORTED, ACCELERATOR_INPUT_OPEN, DIRECTION_COMMAND, INVERTER_RESPONSE_TIMEOUT,
	HARDWARE_GATE_DESATURATION, HARDWARE_OVERCURRENT, UNDERVOLTAGE, CAN_COMMAND_MESSAGE_LOST,
	MOTOR_OVERTEMPERATURE, BRAKE_INPUT_SHORTED = 16, BRAKE_INPUT_OPEN, MODULE_A_OVERTEMPERATURE,
	MODULE_B_OVERTEMPERATURE, MODULE_C_OVERTEMPERATURE, PCB_OVERTEMPERATURE, GATE_DRIVE_BOARD_1_OVERTEMPERATURE,
	GATE_DRIVE_BOARD_2_OVERTEMPERATURE, GATE_DRIVE_BOARD_3_OVERTEMPERATURE, CURRENT_SENSOR, RESOLVER_NOT_CONNECTED = 30
};

enum class InternalStates : uint8_t {
	InverterEnableState, InverterEnableLockout, BMSActive, BMSLimitingTorque, Count
};

} // namespace drivers::inverter
